### ISSUE TITLE
problems with gcc with c++20

### ISSUE THREAD

**Issue by mmorale3** [gabime/spdlog#2361]
The following simple example doesn't compile with gcc-11.2 with c++20 (only tested 11.2, should fail with other gcc versions too). Works with clang-12.0. It works fine with both compilers and c++17. This used to work fine with v1.8 (found the problem when I upgraded to the latest version).

#include "spdlog/spdlog.h"
template<class... Args>
void app_log(Args&&... args)
{
  spdlog::info(std::forward<Args>(args)...);
}
int main()
{
  {
    spdlog::info("Direct no fmt.");
    spdlog::info("Direct w ftm {}.",1);
  }
  app_log("log no fmt.");
  app_log("log w fmt {}",1);
  return 0;
}

I get the following error:
test.cpp: In instantiation of 'void app_log(Args&& ...) [with Args = {const char (&)[13], int}]':
test.cpp:16:10:   required from here
test.cpp:6:15: error: 'args#0' is not a constant expression
    6 |   spdlog::info(std::forward<Args>(args)...);

**Comment by tt4g** [comment]
It looks like you just forgot to specify the `T` template parameter of `std::forward<T>`, which has nothing to do with spdlog.

```diff
 #include "spdlog/spdlog.h"
+
+#include <utility>
+
 template<class... Args>
 void app_log(Args&&... args)
 {
-    spdlog::info(std::forward(args)...);
+    spdlog::info(std::forward<Args>(args)...);
 }
 int main()
 {
     {
         spdlog::info("Direct no fmt.");
         spdlog::info("Direct w ftm {}.",1);
     }
     app_log("log no fmt.");
     app_log("log w fmt {}",1);
     return 0;
 }
```

**Comment by tguenth** [comment]
The error message was a bit misleading. Switching the compiler to clang confirmed this problem.

When trying the approach described above, the problem persisted. https://github.com/gabime/spdlog/issues/2361#issuecomment-1120143064

`spdlog` does populate `format_string` from `libfmt` on its interfaces. For cpp20 the constructor `fmt::format_string` is declared for `consteval`, which forces to compiler to evaluate at compile time. This is where the observed error occurs.

For my understanding the context of `app_log` is not evaluated at compile time because `app_log` is not declared as `constexpr`.
Adding `constexpr` to `app_log` will not have the desired effect, since `spdlog::info` is not itself contexpr. 

To overcome this problem, you need a vehicle that is guaranteed to be evaluated at compile time, even within the context of `app_log` which is not evaluated at compile time. Passing a format string as `fmt::format_string` with a consteval constructor does just that.
Check this handy approach from here https://stackoverflow.com/a/69647103 to fix the reproducer.

With the following changes, the compilation works for gcc, clang, and various versions of spdlog using either the bundled or an external libfmt.

``` diff
#include "spdlog/spdlog.h"
+
+#include <utility>
+
 template<class... Args>
- void app_log(Args&&... args)
+ void app_log(fmt::format_string<Args...> fmt, Args&&... args)
 {
-    spdlog::info(std::forward(args)...);
+    spdlog::info(fmt, std::forward<Args>(args)...);
 }
 int main()
 {
     {
         spdlog::info("Direct no fmt.");
         spdlog::info("Direct w ftm {}.",1);
     }
     app_log("log no fmt.");
     app_log("log w fmt {}",1);
     return 0;
 }

```
