### ISSUE TITLE
1.9.1 and 1.9.2 fail to build with fmt 7.1.3

### ISSUE THREAD

**Issue by heinemml** [gabime/spdlog#2050]
From what I understand spdlog 1.9.x should be buildable with fmt 7.x. This is true for 1.9.0 but 1.9.1 and 1.9.2 fail.

Built with GCC 10.2.0 and fmt 7.1.3 with `-DSPDLOG_BUILD_TESTS=OFF -DSPDLOG_BUILD_EXAMPLE=OFF -DSPDLOG_BUILD_BENCH=OFF -DSPDLOG_FMT_EXTERNAL=ON -DSPDLOG_BUILD_SHARED=ON`:

1.9.1 misses `fmt::format_string` added in #2008
```
[ 42%] Building CXX object CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
In file included from /build/build/spdlog-1.9.1/include/spdlog/spdlog.h:12,
                 from /build/build/spdlog-1.9.1/include/spdlog/spdlog-inl.h:7,
                 from /build/build/spdlog-1.9.1/src/spdlog.cpp:8:
/build/build/spdlog-1.9.1/include/spdlog/common.h:141:72: error: 'format_string' is not a member of 'fmt'
  141 |     : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
      |                                                                        ^~~~~~~~~~~~~
/build/build/spdlog-1.9.1/include/spdlog/common.h:141:72: error: 'format_string' is not a member of 'fmt'
/build/build/spdlog-1.9.1/include/spdlog/common.h:141:85: error: template argument 2 is invalid
  141 |     : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
      |                                                                                     ^
/build/build/spdlog-1.9.1/include/spdlog/common.h:141:86: error: template argument 2 is invalid
  141 |     : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
      |                                                                                      ^~
/build/build/spdlog-1.9.1/include/spdlog/common.h:141:88: error: '<declaration error>' is not a template [-fpermissive]
  141 |     : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
      |                                                                                        ^~
/build/build/spdlog-1.9.1/include/spdlog/common.h:141:90: error: expected '{' before 'value'
  141 |     : std::integral_constant<bool, std::is_convertible<const T &, fmt::format_string<>>::value || is_convertible_to_wformat_string<T>::value>
      |                                                                           
```

1.9.2 adds a dependency on `fmt::basic_runtime` from #2037:
```
[ 42%] Building CXX object CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
In file included from /build/build/spdlog-1.9.2/include/spdlog/logger.h:17,
                 from /build/build/spdlog-1.9.2/include/spdlog/async_logger.h:17,
                 from /build/build/spdlog-1.9.2/include/spdlog/async.h:17,
                 from /build/build/spdlog-1.9.2/src/stdout_sinks.cpp:11:
/build/build/spdlog-1.9.2/include/spdlog/common.h:127:111: error: 'basic_runtime' is not a member of 'fmt'
  127 |           std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
      |                                                                                                               ^~~~~~~~~~~~~
/build/build/spdlog-1.9.2/include/spdlog/common.h:127:111: error: 'basic_runtime' is not a member of 'fmt'
/build/build/spdlog-1.9.2/include/spdlog/common.h:127:125: error: template argument 2 is invalid
  127 |           std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
      |                                                                                                                             ^~~~
/build/build/spdlog-1.9.2/include/spdlog/common.h:127:138: error: expected '{' before '>' token
  127 |           std::is_convertible<T, fmt::basic_string_view<Char>>::value || std::is_same<remove_cvref_t<T>, fmt::basic_runtime<Char>>::value>
      |                                                                                                                                          ^
```

**Comment by gabime** [comment]
Thanks for reporting.  If you find the right ifdef combination for this to work with 7.1 please open a PR or update here.

**Comment by gabime** [comment]
No such plan. This version needs a newer fmt version.
