### ISSUE TITLE
Conflict with Boost.Asio on Windows

### ISSUE THREAD

**Issue by gcerretani** [gabime/spdlog#1663]
Same as issue #179, marked as fixed in 2016, but reappeared since v1.6.0.

This source code

```
#include <spdlog/spdlog.h>
#include <boost/asio.hpp>
```

compiles in v1.5.0, but fails since v1.6.0 with messages like

>  fatal error C1189: #error:  WinSock.h has already been included.

 Tested up to v1.8.0 with Boost v1.67 and MSVC 1900 (2015).

**Comment by tt4g** [comment]
`windows.h` includes `winsock.h`.
This is causing Boost.Asio to generate a compile error.
Boost.Asio uses Winsock2, so `winsock.h` should not be included.

This is the root cause of the `windows.h` definition, and is not a problem that can be addressed by spdlog alone.

Workaround: `#define _WINSOCKAPI_` or `#define WIN32_LEAN_AND_MEAN` before `#include <windows.h`.
Another way, `#include <boost/asio.hpp>` before `#include <spdlog/spdlog.h>`.

Refer: [c \- Cannot include both files \(WinSock2, Windows\.h\) \- Stack Overflow](https://stackoverflow.com/questions/21399650/cannot-include-both-files-winsock2-windows-h)

**Comment by gabime** [comment]
Strange that it appears in 1.8.0 though.. Are you using the bundled fmt version 7.0.3?

**Comment by gcerretani** [comment]
Investigating, I've found that problems arise when compiling with **NOMINMAX** defined.

Source code:
```
#include <spdlog/spdlog.h>
#include <boost/asio.hpp>
int main() {}
```

Preprocessor definitions:

- NOMINMAX
- BOOST_ALL_NO_LIB
- _WIN32_WINNT=0x0601
- BOOST_ERROR_CODE_HEADER_ONLY
- BOOST_SYSTEM_NO_DEPRECATED

Compiler output:

```
1>------ Build started: Project: Playing++, Configuration: Debug x64 ------
1>Build started 9/3/2020 8:52:59 AM.
1>     1>
1>InitializeBuildStatus:
1>         Touching "x64\Debug\Playing++.tlog\unsuccessfulbuild".
1>       ClCompile:
1>         Playing++.cpp
1>     1>
1>e:\external\boost_1_67_0\boost\asio\detail\socket_types.hpp(24): fatal error C1189: #error:  WinSock.h has already been included
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:02.34
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Removing **NOMIXMAX** from preprocessors everything works (with only two C4996 warnings). Keeping **NOMINMAX**, both @tt4g solutions (swapping includes and adding **WIN32_LEAN_AND_MEAN**) works.

**Comment by tt4g** [comment]
> Removing NOMIXMAX from preprocessors everything works

It seems that `format-inl` includes `windows.h` but does not defined `WIN32_LEAN_AND_MEAN` when only `NOMINMAX` macro is defined.

https://github.com/gabime/spdlog/blob/4a9ccf7e38e257feecce0c579a782741254eaeef/include/spdlog/fmt/bundled/format-inl.h#L25-L36

This is a bit tricky.
We need to get all the patterns that branches off by defining `WIN32_LEAN_AND_MEAN` and `NOMINMAX` to be addressed.

**Comment by tt4g** [comment]
@gcerretani Currently I don't have a machine at hand that can do C++ development.

Can you confirm that the following patch will no longer reproduce the problem?

```diff
 #ifdef _WIN32 
 #  if !defined(NOMINMAX) && !defined(WIN32_LEAN_AND_MEAN) 
 #    define NOMINMAX 
 #    define WIN32_LEAN_AND_MEAN 
 #    include <windows.h> 
 #    undef WIN32_LEAN_AND_MEAN 
 #    undef NOMINMAX 
+#  elif defined(NOMINMAX) && !defined(WIN32_LEAN_AND_MEAN) 
+#    define WIN32_LEAN_AND_MEAN 
+#    include <windows.h> 
+#    undef WIN32_LEAN_AND_MEAN 
 #  else
 #    include <windows.h> 
 #  endif 
 #  include <io.h> 
 #endif 
```

**Comment by gabime** [comment]
@tt4g Good catch. Seems you are right!

**Comment by gcerretani** [comment]
That patch resolve the problem.

**Comment by gabime** [comment]
@gcerretani Could you open a PR in the  fmt repo to fix this?

**Comment by gcerretani** [comment]
I think I've done it.

**Comment by gabime** [comment]
Thanks. Will be updated in spdlog's copy when next official fmt is released

**Comment by drewhamiltonasdf** [comment]
I am having this problem with the latest boost release 1.80.0. I used the patch above and I'm back in business, as follows:

```
#ifdef _WIN32 
#  if !defined(NOMINMAX) && !defined(WIN32_LEAN_AND_MEAN) 
#    define NOMINMAX 
#    define WIN32_LEAN_AND_MEAN 
#    include <windows.h> 
#    undef WIN32_LEAN_AND_MEAN 
#    undef NOMINMAX 
#  elif defined(NOMINMAX) && !defined(WIN32_LEAN_AND_MEAN)
#    define WIN32_LEAN_AND_MEAN
#    include <windows.h>
#    undef WIN32_LEAN_AND_MEAN
#  else
#    include <windows.h> 
#  endif 
#  include <io.h> 
#endif 

#include <boost/asio.hpp>
```


I will probably disappear and be unresponsive if anyone gets back to me. Just being honest. I'm not on GitHub every day...
