### ISSUE TITLE
 undefined reference to `fmt::v9::detail::assert_fail(char const*, int, char const*)' when build using version 1.12.0

### ISSUE THREAD

**Issue by Je2ry** [gabime/spdlog#3032]
Hi,
     I'm integrating spdlog as header-only into my project and I'm getting compile errors:
     undefined reference to fmt::v9::detail::assert_fail(char const*, int, char const*)
    Besides, I don't want to use external fmt library or std::format.
