### ISSUE TITLE
spdlog does not build with latest fmt lib

### ISSUE THREAD

**Issue by dpriedel** [gabime/spdlog#1604]
Trying to build spdlog using external fmt library yields the following error:

[ 12%] Building CXX object CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
In file included from /extra/spdlog/spdlog/include/spdlog/pattern_formatter-inl.h:10,
                 from /extra/spdlog/spdlog/src/spdlog.cpp:13:
/extra/spdlog/spdlog/include/spdlog/details/fmt_helper.h: In function ‘unsigned int spdlog::details::fmt_helper::count_digits(T)’:
/extra/spdlog/spdlog/include/spdlog/details/fmt_helper.h:37:43: error: ‘fmt::internal’ has not been declared
   37 |     return static_cast<unsigned int>(fmt::internal::count_digits(static_cast<count_type>(n)));

and fails to build

**Comment by candrews** [comment]
I also can confirmed this failure; spdlog 1.6.1 fails to build with [libfmt 7.0.0](https://github.com/fmtlib/fmt/releases/tag/7.0.0).

**Comment by candrews** [comment]
Pull request addressing this issue: https://github.com/gabime/spdlog/pull/1605
