### ISSUE TITLE
usage of constexpr causes compiler failures

### ISSUE THREAD

**Issue by gocarlos** [gabime/spdlog#655]
this minimal example shows the problem: 

```cpp
#include <iostream>
#include <memory>
#include <thread>

#include "spdlog/spdlog.h"

class WebServer
{
public:
  static constexpr unsigned int _port = 9980u;
};

int main(int argc, char **argv)
{
  std::vector<spdlog::sink_ptr> sinks;
  sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_st>());
  sinks.push_back(std::make_shared<spdlog::sinks::daily_file_sink_st>("/tmp/asdf", 23, 59));
  auto logger = std::make_shared<spdlog::logger>("logger", begin(sinks), end(sinks));
  spdlog::register_logger(logger);
  logger->flush_on(spdlog::level::warn);


  // error
  logger->info("asdf {}", WebServer::_port); 
  // ok
  logger->info("asdf {}", std::to_string(WebServer::_port));

  return 0;
}

```
```text
CMakeFiles/asfdasdf.dir/src/main.cpp.o: In function `void spdlog::logger::info<unsigned short>(char const*, unsigned short const&)':
asdfasdfasfdasdf/third_party/spdlog/include/spdlog/details/logger_impl.h:145: undefined reference to `WebServer::_port'
asdfasdfasfdasdf/third_party/spdlog/include/spdlog/details/logger_impl.h:145: undefined reference to `WebServer::_port'
collect2: error: ld returned 1 exit status
CMakeFiles/asfdasdf.dir/build.make:94: recipe for target 'asfdasdf' failed
make[2]: *** [asfdasdf] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/asfdasdf.dir/all' failed
make[1]: *** [CMakeFiles/asfdasdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Cmake for reference 

```cmake
cmake_minimum_required(VERSION 3.7.2 FATAL_ERROR)

project(asfdasdf CXX C)

# Set the language standard be 11 for C and 14 for C++
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 14)
enable_language(C CXX)

find_package(Threads REQUIRED)

add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/third_party/spdlog)

add_executable(${PROJECT_NAME}
  src/main.cpp
)
target_link_libraries(${PROJECT_NAME}
  PRIVATE
  Threads::Threads
  spdlog
)
```

```bash
asdfasdfasfdasdf$ tree -L 3
.
├── build
│   ├── ....
├── build.sh
├── CMakeLists.txt
├── src
│   └── main.cpp
└── third_party
    └── spdlog
        ├── appveyor.yml
        ├── astyle.sh
        ├── bench
        ├── cmake
        ├── CMakeLists.txt
        ├── example
        ├── include
        ├── INSTALL
        ├── LICENSE
        ├── README.md
        └── tests

16 directories, 26 files
```

Do I miss something?

**Comment by gabime** [comment]
which compiler is it?

**Comment by gocarlos** [comment]
Gcc 6.3 on debian 9

**Comment by godbyk** [comment]
It fails to build for me with C++14 but works with C++17 (using clang++ 5.0.0).

@gocarlos If you pass `-std=c++17` to `g++`, does it work okay?

**Comment by gocarlos** [comment]
@godbyk yeah:
* with gcc 6.3 you cannot compile with C++17 (debian 9)
* with gcc 7.3 it works with C++ 17, but still not with C++14 (ubuntu 18.04 beta)

This means basically that distros like debian 9, ubuntu 16.04 etc are affected by this problem as most of the projects are still using c++14

**Comment by gabime** [comment]
@gocarlos In any case this issue is not directly related to spdlog, right?

**Comment by godbyk** [comment]
@gocarlos No, it's a subtle bug in your code.

You need to add a definition for `WebServer::_port` when using C++14 and earlier (see below).  With C++17, `static constexpr` member variables are implicitly declared `inline` and do not require an namespace-scope definition (but are still allowed to have one).

See the last couple paragraphs of [this documentation](http://en.cppreference.com/w/cpp/language/static#Constant_static_members) for details.

To make the code work, just add `constexpr unsigned int WebServer::_port;` after the class definition:

```c++
#include <iostream>
#include <memory>
#include <thread>

#include "spdlog/spdlog.h"

class WebServer
{
public:
  static constexpr unsigned int _port = 9980u;
};

// required for C++14
constexpr unsigned int WebServer::_port;

int main(int argc, char **argv)
{
  std::vector<spdlog::sink_ptr> sinks;
  sinks.push_back(std::make_shared<spdlog::sinks::stdout_sink_st>());
  sinks.push_back(std::make_shared<spdlog::sinks::daily_file_sink_st>("/tmp/asdf", 23, 59));
  auto logger = std::make_shared<spdlog::logger>("logger", begin(sinks), end(sinks));
  spdlog::register_logger(logger);
  logger->flush_on(spdlog::level::warn);


  // error
  logger->info("asdf {}", WebServer::_port);
  // ok
  logger->info("asdf {}", std::to_string(WebServer::_port));

  return 0;
}
```

**Comment by gocarlos** [comment]
@godbyk Thanks for the explanatory comment, I didn't knew that. 
Was interesting that using to_string also solves the problem. 

So, closing this issue as it seems like solved. 

Thanks for the great lib again, looking forward to see it in the C++ standard  :+1:
