### ISSUE TITLE
compile error after pull commit 8bf71867

### ISSUE THREAD

**Issue by gzliudan** [gabime/spdlog#1978]
After update to commit 8bf71867 today, the below compile error occurs:  
```cpp
In file included from ....../src/Logger.cpp:1:
In file included from ....../gabime/spdlog/include/spdlog/sinks/daily_file_sink.h:6:
In file included from ....../gabime/spdlog/include/spdlog/common.h:276:
....../gabime/spdlog/include/spdlog/common-inl.h:19:22: error: constexpr variable 'level_string_views' must be initialized by a constant expression
static string_view_t level_string_views[] SPDLOG_LEVEL_NAMES;
                     ^                    ~~~~~~~~~~~~~~~~~~
....../gabime/spdlog/include/spdlog/fmt/bundled/core.h:456:15: note: non-constexpr function 'strlen' cannot be used in a constant expression
      size_ = std::strlen(reinterpret_cast<const char*>(s));
              ^
....../gabime/spdlog/include/spdlog/common-inl.h:19:43: note: in call to 'basic_string_view(&"trace"[0])'
static string_view_t level_string_views[] SPDLOG_LEVEL_NAMES;
                                          ^
....../gabime/spdlog/include/spdlog/common.h:186:9: note: expanded from macro 'SPDLOG_LEVEL_NAMES'
        SPDLOG_LEVEL_NAME_TRACE, SPDLOG_LEVEL_NAME_DEBUG, SPDLOG_LEVEL_NAME_INFO, SPDLOG_LEVEL_NAME_WARNING, SPDLOG_LEVEL_NAME_ERROR, SPDLOG_LEVEL_NAME_CRITICAL, SPDLOG_LEVEL_NAME_OFF                                                                    \
        ^
....../gabime/spdlog/include/spdlog/common.h:156:33: note: expanded from macro 'SPDLOG_LEVEL_NAME_TRACE'
#define SPDLOG_LEVEL_NAME_TRACE "trace"
                                ^
```

**Comment by gabime** [comment]
do you compile with c++17/20 flag

**Comment by gzliudan** [comment]
Yes I'm using C++17:
```bash
clang --version
Ubuntu clang version 11.0.0-2~ubuntu20.04.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by Jamaika1** [comment]
```
In file included from c:\msys1200\x86_64-w64-mingw32\include\spdlog\spdlog.h:12,
                 from common.h:43,
                 from BMPFormat.cpp:28:
c:\msys1200\x86_64-w64-mingw32\include\spdlog\common-inl.h:19:43: error: 'constexpr fmt::v8::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]' called in a constant expression
   19 | static string_view_t level_string_views[] SPDLOG_LEVEL_NAMES;
      |                                           ^~~~~~~~~~~~~~~~~~
In file included from c:\msys1200\x86_64-w64-mingw32\include\spdlog\fmt\fmt.h:22,
                 from c:\msys1200\x86_64-w64-mingw32\include\spdlog\common.h:36,
                 from c:\msys1200\x86_64-w64-mingw32\include\spdlog\spdlog.h:12,
                 from common.h:43,
                 from BMPFormat.cpp:28:
c:\msys1200\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:453:3: note: 'constexpr fmt::v8::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]' is not usable as a 'constexpr' function because:
  453 |   basic_string_view(const Char* s) : data_(s) {
      |   ^~~~~~~~~~~~~~~~~
```
GCC 12.0 C++17 JPEG2000 Grok

**Comment by bb1950328** [comment]
Similar error for me:
```
In file included from ../../src/lib/spdlog/include/spdlog/spdlog.h:14,
                 from ../../src/db.cpp:2:
../../src/lib/spdlog/include/spdlog/logger.h: In instantiation of ‘void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, const FormatString&, Args&& ...) [with FormatString = fmt::v8::basic_string_view<char>; Args = {int&}]’:
../../src/lib/spdlog/include/spdlog/logger.h:88:13:   required from ‘void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {int&}; spdlog::string_view_t = fmt::v8::basic_string_view<char>]’
../../src/lib/spdlog/include/spdlog/logger.h:94:12:   required from ‘void spdlog::logger::log(spdlog::level::level_enum, const FormatString&, Args&& ...) [with FormatString = char [35]; Args = {int&}]’
../../src/lib/spdlog/include/spdlog/logger.h:112:12:   required from ‘void spdlog::logger::info(const FormatString&, Args&& ...) [with FormatString = char [35]; Args = {int&}]’
../../src/lib/spdlog/include/spdlog/spdlog.h:157:31:   required from ‘void spdlog::info(const FormatString&, Args&& ...) [with FormatString = char [35]; Args = {int&}]’
../../src/db.cpp:15:25:   required from here
../../src/lib/spdlog/include/spdlog/logger.h:341:27: error: ‘fmt’ is not a constant expression
  341 |             fmt::format_to(buf, fmt, std::forward<Args>(args)...);
      |             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

My code:
```cpp
void foo(int bar) {
    spdlog::info("foo {}", bar);
}
```
I'm using C++20 with gcc 11.1.0.

**Comment by gabime** [comment]
Fixed.  I hope. @gzliudan, @bb1950328 and @Jamaika1 please feedback if latest commit this solves it.

**Comment by Jamaika1** [comment]
Something is wrong. The codec is building up, but it doesn't work properly. Let other developers analyze the compatibility problem. 
https://github.com/GrokImageCompression/grok/issues/252

**Comment by gabime** [comment]
@Jamaika1 seems you posted in the wring place

**Comment by bb1950328** [comment]
Works on `gcc 11.1.0` and C++20 with commit [`cdad84aa46`](https://github.com/gabime/spdlog/commit/cdad84aa469a09b2e33902bc5d076097ec5071c7)

**Comment by candrews** [comment]
Shall a release be made?

**Comment by gzliudan** [comment]
The bug is fixed, this issue can be closed.

**Comment by shazni** [comment]
I tried to build v1.11.0 on both Fedora 37 and Ubuntu 22.04. This issue still exists. For me it came in for both -std=c++20 and -std=c++17. Here are gcc versions:

Fedora 37 - gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Ubuntu 22.04 - gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by Jamaika1** [comment]
For C++20, use the latest version of gcc13.
I have no problem with SPDLOG_LEVEL_NAMES in Windows10 with grok HTJPEG2000 C++20.
When using C++20 you should use std::format with SPDLOG_USE_STD_FORMAT.
And there are other problems here, but that's the worry of software developers.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108062

**Comment by shazni** [comment]
Previously I settled with v1.8.5 instead of trying this with C++20 and gcc13 as you suggested. That's because gcc13 wasn't available as an officially released package in Fedora 37 which I was using before. 

Now that Fedora 38 is released which has gcc13 available. I tried building with C++20 and -DSPDLOG_USE_STD_FORMAT=ON. The library builds but there are bunch of failures in example.cpp. 

I opened a new issues [here](https://github.com/gabime/spdlog/issues/2724) as the error seems to be different.
