### ISSUE TITLE
compile error when print user defined type with v1.10.0 or higher

### ISSUE THREAD

**Issue by subenle-nreal** [gabime/spdlog#2777]
I want to print MyVector3f by by implementing operator<<, it works well with spdlog of version v1.9.2, but will get a compile error when upgrade to version v1.10.0. It seems that the class `is_streamable` in `spdlog/fmt/bundled/ostream.h` was changed in v1.10.0.

complie error：
```text
enableif.cpp:25:11: error: no member named 'x' in 'fmt::basic_string_view<char>'
        v.x() = this->x;
        ~ ^
/spdlog/include/spdlog/fmt/bundled/core.h:1373:41: note: in instantiation of function template specialization 'MyVector3f::operator basic_string_view<fmt::basic_string_view<char>>' requested here
    return basic_string_view<char_type>(val);
                                        ^
/spdlog/include/spdlog/logger.h:90:9: note: in instantiation of function template specialization 'spdlog::logger::log_<MyVector3f &>' requested here
        log_(loc, lvl, fmt, std::forward<Args>(args)...);
        ^
/spdlog/include/spdlog/logger.h:96:9: note: in instantiation of function template specialization 'spdlog::logger::log<MyVector3f &>' requested here
        log(source_loc{}, lvl, fmt, std::forward<Args>(args)...);
        ^
/spdlog/include/spdlog/logger.h:158:9: note: in instantiation of function template specialization 'spdlog::logger::log<MyVector3f &>' requested here
        log(level::info, fmt, std::forward<Args>(args)...);
        ^
/spdlog/include/spdlog/spdlog.h:157:27: note: in instantiation of function template specialization 'spdlog::logger::info<MyVector3f &>' requested here
    default_logger_raw()->info(fmt, std::forward<Args>(args)...);
                          ^
enableif.cpp:41:13: note: in instantiation of function template specialization 'spdlog::info<MyVector3f &>' requested here
    spdlog::info("v3 {}", v3);
            ^
enableif.cpp:26:11: error: no member named 'y' in 'fmt::basic_string_view<char>'
        v.y() = this->y;
        ~ ^
enableif.cpp:27:11: error: no member named 'z' in 'fmt::basic_string_view<char>'
        v.z() = this->z;
        ~ ^
3 errors generated.
```

code is list below：

```cpp
#include <iostream>
#include <type_traits>
#include <spdlog/spdlog.h>
#include <spdlog/fmt/ostr.h>
using namespace std;

class MyVector3f {
   public:
    float x = 1;
    float y = 2;
    float z = 3;

   public:
    MyVector3f() {}
    template <typename LocalType>
    MyVector3f(const LocalType& v) {
        this->x = v.x();
        this->y = v.y();
        this->z = v.z();
    }

    template <typename LocalType>
    operator LocalType() const {
        LocalType v;
        v.x() = this->x;
        v.y() = this->y;
        v.z() = this->z;
        return v;
    }

    template <typename OStream>
    friend OStream& operator<<(OStream& os, const MyVector3f& v) {
        return os << "["
                  << " x:" << v.x << ", y:" << v.y << ", z:" << v.z << "]";
    }
};

int main()
{
    MyVector3f v3;
    spdlog::info("v3 {}", v3);
    return 0;
}
```

**Comment by tt4g** [comment]
Due to specification change in fmt library.
See fmtlib/fmt#3465, fmtlib/fmt#2357

**Comment by subenle-nreal** [comment]
> Due to specification change in fmt library. See #3465, #2357

thanks, I've confirmed that the issue was introduced in fmt version 8.1.1.

**Comment by tt4g** [comment]
> Due to specification change in fmt library. See #3465, #2357

Oops. I'm forgot fmtlib/fmt prefix.
Comment updated.
