### ISSUE TITLE
spdlog make issues in centos 7

### ISSUE THREAD

**Issue by Hakai-Shin** [gabime/spdlog#2834]
make fails with following error while building spdlog in centos 7
![image](https://github.com/gabime/spdlog/assets/54961206/86e69612-8a36-44b9-ae88-90293e207c56)

**Comment by Hakai-Shin** [comment]
This issue is occuring while building examples. So, If any body plans to use the build library for faster compilation  use

cmake -DSPDLOG_BUILD_SHARED=ON -DSPDLOG_BUILD_EXAMPLE=NO -DSPDLOG_ENABLE_PCH=ON -DCMAKE_INSTALL_PREFIX=../. .

**Comment by Hakai-Shin** [comment]
Build was successful after using following command 
cmake -DSPDLOG_BUILD_SHARED=ON -DSPDLOG_BUILD_EXAMPLE=NO -DSPDLOG_ENABLE_PCH=ON -DCMAKE_INSTALL_PREFIX=../. .

but while running a  different sample code using the build library causing same error

**Comment by tt4g** [comment]
Do not attach images. Other users will not be able to search for this issue from the error message.

**Comment by tt4g** [comment]
> error: `put_time` is not a member of `std`

Duplicate #2333, #2666

The compiler version is not provided, but from the error, I assume it is GCC 4.8 (the latest version  on CentOS 7).
GCC 4.8 is not supported because it does not fully support C++11.

- [54354 – TODO extended iomanip manipulators std::get\_time and std::put\_time \(C\+\+11, section 27\.7\.5\)](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354)
- [c\+\+ \- std::put\_time implementation status in GCC? \- Stack Overflow](https://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc)

> error: specialization of ‘template<class T, class Char, class Enable> struct fmt::v9::formatter’ in different namespace [-fpermissive]

Duplicate #2835

**Comment by alexisfrjp** [comment]
> > error: `put_time` is not a member of `std`
> 
> Duplicate #2333, #2666
> 
> The compiler version is not provided, but from the error, I assume it is GCC 4.8 (the latest version on CentOS 7). GCC 4.8 is not supported because it does not fully support C++11.
> 
>     * [54354 – TODO extended iomanip manipulators std::get_time and std::put_time (C++11, section 27.7.5)](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354)
> 
>     * [c++ - std::put_time implementation status in GCC? - Stack Overflow](https://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc)
> 
> 
> > error: specialization of ‘template<class T, class Char, class Enable> struct fmt::v9::formatter’ in different namespace [-fpermissive]
> 
> Duplicate #2835

In that case, what is the latest version of the library that is supported on Centos/RHEL 7?

**Comment by alexisfrjp** [comment]
v1.9.2 is the latest version you can compile with gcc 4.8
