### ISSUE TITLE
MSVC prompts errors when I try to compile a cpp included spdlog headers

### ISSUE THREAD

**Issue by XY-ShadowK** [gabime/spdlog#3300]
I use `cl mySrc.cpp /I spdlog-1.14.1/include` then got tips below.
```command
spdlog-1.14.1/include/spdlog/details/null_mutex.h(10): error C2059: syntax error: 'namespace'
spdlog-1.14.1/include/spdlog/details/null_mutex.h(10): error C2143: syntax error: missing ';' before '{'
spdlog-1.14.1/include/spdlog/details/null_mutex.h(10): error C2447: '{': missing function header (old-style formal list?)
spdlog-1.14.1/include/spdlog/fmt/bundled/format.h(2742): error C2039: '_finite': is not a member of 'std'
Microsoft/VisualStudio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/include/functional(31): note: see declaration of 'std'
spdlog-1.14.1/include/spdlog/fmt/bundled/format-inl.h(1412): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
spdlog-1.14.1/include/spdlog/details/console_globals.h(21): error C2061: syntax error: identifier 'null_mutex'
spdlog-1.14.1/include/spdlog/details/console_globals.h(22): error C2143: syntax error: missing ';' before '&'
spdlog-1.14.1/include/spdlog/details/console_globals.h(22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
spdlog-1.14.1/include/spdlog/details/console_globals.h(22): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
spdlog-1.14.1/include/spdlog/sinks/basic_file_sink.h(36): error C2039: 'null_mutex': is not a member of 'spdlog::details'
spdlog-1.14.1/include/spdlog/details/file_helper-inl.h(21): note: see declaration of 'spdlog::details'
spdlog-1.14.1/include/spdlog/sinks/basic_file_sink.h(36): error C2065: 'null_mutex': undeclared identifier
spdlog-1.14.1/include/spdlog/sinks/basic_file_sink.h(36): error C2923: 'spdlog::sinks::basic_file_sink': 'null_mutex' is not a valid template type argument for parameter 'Mutex'
spdlog-1.14.1/include/spdlog/sinks/basic_file_sink.h(36): note: see declaration of 'null_mutex'
```
I removed all my logic code, this cpp file just has include lines as below.
```c++
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
```
What can I do to solve this problem?

**Comment by gabime** [comment]
Try adding the /std=c++11 flag

**Comment by XY-ShadowK** [comment]
```command
cl : Command line warning D9002 : ignoring unknown option '/std:c++11'
cl : Command line warning D9002 : ignoring unknown option '/std=c++11'
cl : Command line warning D9002 : ignoring unknown option '-std:c++11'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
```
So does it means VS BuildTool 2019 can not use c++11?
Should I try 2017 or are there other solutions ?
What compiler do you use on Windows platform to build it?

**Comment by gabime** [comment]
try /std:c++17

**Comment by XY-ShadowK** [comment]
Now the include-only cpp can be complied in specific circumstances, it still makes errors in some cases when add them to main program.
### Descption
My project can be compiled without warns and errors with these includes removed.
The `jsonProcesser.cpp` uses jsoncpp lib and can be compiled separately or with main program.
### case 1 Puts include lines like below
```c++
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
#include "myHeader.hpp"
#include "jsonProcesser.cpp"
```
Got ↓
```command
spdlog-1.14.1\include\spdlog\fmt\bundled\format-inl.h(1412): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
myHeader.hpp(22): error C2065: 'byte': undeclared identifier
myHeader.hpp(22): error C2065: 'byte': undeclared identifier
myHeader.hpp(22): error C2440: 'initializing': cannot convert from 'initializer list' to 'bool'
myHeader.hpp(22): note: The initializer contains too many elements
```
It prompts errors in myHeader.
### case 2 Puts include lines like below
```c++
#include "myHeader.hpp"
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
#include "jsonProcesser.cpp"
```
Got ↓
```command
spdlog-1.14.1\include\spdlog\fmt\bundled\format-inl.h(1412): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```
It prompts the warning and compiled successfully.
### case 3 Puts include lines like below
```c++
#include "myHeader.hpp"
#include "jsonProcesser.cpp"
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
```
Got ↓
```command
spdlog-1.14.1\include\spdlog\fmt\bundled\format.h(2742): error C2039: '_finite': is not a member of 'std'
Microsoft\VisualStudio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\functional(31): note: see declaration of 'std'
spdlog-1.14.1\include\spdlog\fmt\bundled\format-inl.h(1412): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```
It prompts the errors in spdlog.

How can I solve it, or should I just uses in the specific order(case 2)?

**Comment by tt4g** [comment]
> ```
> spdlog-1.14.1\include\spdlog\fmt\bundled\format-inl.h(1412): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
> ```

As the warning message states, it is because you have not specified the `/EHsc` option in your project: https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4530?view=msvc-170

> It prompts the errors in spdlog.
>
> How can I solve it, or should I just uses in the specific order(case 2)?

If the problem occurs in the order of header inclusion, then there is a problem with the immediately preceding included header.
I expect this is due to the presence of bad code that should be avoided in C++, such as `using namespace std;`, in header files `included` before spdlog.

**Comment by XY-ShadowK** [comment]
> > It prompts the errors in spdlog.
> > How can I solve it, or should I just uses in the specific order(case 2)?
> 
> If the problem occurs in the order of header inclusion, then there is a problem with the immediately preceding included header. I expect this is due to the presence of bad code that should be avoided in C++, such as `using namespace std;`, in header files `included` before spdlog.

I checked `myHeader.hpp` and it has no `using namespace` or other `using` statements. It and headers in its include chain just have `#pragma once`, `#ifndef _HEADER_HPP_ #define _HEADER_HPP_ #endif`, constant definitions, namespace declarations, class and function declarations. All members of other namespaces are referred to as :: form.
You can see that compiler prompts errors in `myHeader.hpp` after spdlog headers in case 1 or in spdlog headers after `jsonProcesser.cpp` in case 2. Is it regular? Which file you consider may hides problems?

**Comment by tt4g** [comment]
`using` is just one example of bad code, but there is other bad code that breaks C++ syntax. For example, the use of common words in macro names can break syntax by unintentionally substituting all subsequent words in the preprocessor (the famous `min`/`max` macro in `windows.h`).

We do not know where such bad code is in your project. You have to look carefully for mistakes yourself.

**Comment by XY-ShadowK** [comment]
> We do not know where such bad code is in your project. You have to look carefully for mistakes yourself.

But even if I remove my custom library, it still conflicts with the jsoncpp repository in the inclusion order.
I tried to compile file as below and got errors which is similar to case 3. It can only be compiled if the spdlog is included in preceded by jsoncpp.
```c++
#include <json/json.h>
#include <jsoncpp.cpp>
#include "logProcesser.cpp"
```
Should I submit a issue to jsoncpp or it is just a normal situation for C++ multi-lib collaboration?

**Comment by tt4g** [comment]
Compilation errors in the order of header file inclusion are caused by missing header includes, syntax errors, and missing compile options. These problems are almost always caused by the source code in your project.
Because if there is a problem with the library, we have received reports of the same problem from a number of users, but we have not received any such reports.

**Comment by XY-ShadowK** [comment]
> Compilation errors in the order of header file inclusion are caused by missing header includes, syntax errors, and missing compile options. These problems are almost always caused by the source code in your project. Because if there is a problem with the library, we have received reports of the same problem from a number of users, but we have not received any such reports.

I found out why they conflict. [jsoncpp](https://github.com/open-source-parsers/jsoncpp) uses `isfinite` as its macro name, it caused `std::isfinite` in spdlog to be incorrectly replaced with `_finite` so compiler prompts that `_finite` is not a member of `std`.
I think the only way to use both libraries before they fix the problem is to put the inclusion of spdlog after jsoncpp and I will submit an issue to report problem to them.
Thanks for your patience.
