### ISSUE TITLE
Fails to build against system fmtlib 6.0.0

### ISSUE THREAD

**Issue by jbeich** [gabime/spdlog#1195]
Regressed by https://github.com/fmtlib/fmt/commit/9a777b9e1c610f86f137c7cb3ac18be6eab06cce

```
$ c++ -v
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

$ pkg info -x fmt spdl
libfmt-6.0.0
spdlog-1.3.1_1

$ fgrep -r FMT_VERSION /usr/local/include
/usr/local/include/spdlog/fmt/bundled/core.h:#define FMT_VERSION 50300
/usr/local/include/fmt/core.h:#define FMT_VERSION 60000

$ git describe --tags --always
v1.3.1-509-g3adfeeec
```

```c++
$ cmake -GNinja -DSPDLOG_FMT_EXTERNAL=on .
$ ninja
[...]
FAILED: example/CMakeFiles/example.dir/example.cpp.o
/usr/bin/c++  -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -Iinclude -isystem /usr/local/include -O3 -DNDEBUG   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT example/CMakeFiles/example.dir/example.cpp.o -MF example/CMakeFiles/example.dir/example.cpp.o.d -o example/CMakeFiles/example.dir/example.cpp.o -c example/example.cpp
In file included from example/example.cpp:141:
include/spdlog/fmt/bin_to_hex.h:119:29: fatal error: no member named 'begin' in 'fmt::v6::basic_format_context<std::__1::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>'
        auto inserter = ctx.begin();
                        ~~~ ^
/usr/local/include/fmt/core.h:740:22: note: in instantiation of function template specialization 'fmt::v6::formatter<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> >, char, void>::format<fmt::v6::basic_format_context<std::__1::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>, std::__1::__wrap_iter<const char *> >' requested here
    ctx.advance_to(f.format(*static_cast<const T*>(arg), ctx));
                     ^
/usr/local/include/fmt/core.h:724:21: note: in instantiation of function template specialization 'fmt::v6::internal::value<fmt::v6::basic_format_context<std::__1::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::format_custom_arg<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> >, fmt::v6::formatter<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> >, char, void> >' requested here
    custom.format = format_custom_arg<
                    ^
/usr/local/include/fmt/core.h:1015:10: note: in instantiation of function template specialization 'fmt::v6::internal::value<fmt::v6::basic_format_context<std::__1::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::value<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >' requested here
  return arg_mapper<Context>().map(val);
         ^
/usr/local/include/fmt/core.h:1106:25: note: in instantiation of function template specialization 'fmt::v6::internal::make_arg<true, fmt::v6::basic_format_context<std::__1::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>, spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> >, 0>' requested here
      : data_{internal::make_arg<is_packed, Context>(args)...} {}
                        ^
/usr/local/include/fmt/core.h:1120:10: note: in instantiation of member function 'fmt::v6::format_arg_store<fmt::v6::basic_format_context<std::__1::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>, spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >::format_arg_store' requested here
  return {args...};
         ^
/usr/local/include/fmt/format.h:3347:32: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
                              {make_format_args<context>(args...)});
                               ^
include/spdlog/logger.h:93:13: note: in instantiation of function template specialization 'spdlog::logger::force_log<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >' requested here
            force_log(loc, lvl, fmt, args...);
            ^
include/spdlog/logger.h:100:9: note: in instantiation of function template specialization 'spdlog::logger::log<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >' requested here
        log(source_loc{}, lvl, fmt, args...);
        ^
include/spdlog/logger.h:121:9: note: in instantiation of function template specialization 'spdlog::logger::log<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >' requested here
        log(level::info, fmt, args...);
        ^
include/spdlog/spdlog.h:144:27: note: in instantiation of function template specialization 'spdlog::logger::info<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >' requested here
    default_logger_raw()->info(fmt, args...);
                          ^
example/example.cpp:149:13: note: in instantiation of function template specialization 'spdlog::info<spdlog::details::bytes_range<std::__1::__wrap_iter<const char *> > >' requested here
    spdlog::info("Binary example: {}", spdlog::to_hex(buf));
            ^
1 error generated.
```

**Comment by gabime** [comment]
Thanks @vitaut . Will be fixed soon.

**Comment by gabime** [comment]
Fixed.
