### ISSUE TITLE
spdlog 1.9.2 fails to build with stb_image on Linux gcc 11.1

### ISSUE THREAD

**Issue by qubka** [gabime/spdlog#2248]
Trying to build spdlog 1.9.2-1 with stb_image.h on Linux gcc 11.1 fails with this error:

```
In file included from /home/qubka/Desktop/Vox/lib/stb/stb_image.h:723,
                 from /home/qubka/Desktop/Vox/src/graphics/Image.cpp:3:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/emmintrin.h: In function ‘stbi_uc* stbi__resample_row_hv_2_simd(stbi_uc*, stbi_uc*, stbi_uc*, int, int)’:
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/emmintrin.h:1230:10: error: the last argument must be an 8-bit immediate
 1230 |   return (__m128i)__builtin_ia32_pslldqi128 (__A, __N * 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include/emmintrin.h:1224:10: error: the last argument must be an 8-bit immediate
 1224 |   return (__m128i)__builtin_ia32_psrldqi128 (__A, __N * 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/Vox.dir/build.make:317: CMakeFiles/Vox.dir/src/graphics/Image.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:158: CMakeFiles/Vox.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/Vox.dir/rule] Error 2
make: *** [Makefile:169: Vox] Error 2
```

**Comment by tt4g** [comment]
`stb/stb_image.h` does not exist in spdlog repository.

**Comment by qubka** [comment]
> `stb/stb_image.h` does not exist in spdlog repository.

I know that, my project use it. And spdlog cannot be compiled with stb_image header

**Comment by tt4g** [comment]
The cause of the compilation error is `(__m128i)__builtin_ia32_pslldqi128 (__A, __N * 8)`, which is called in the gcc header file `emmintrin.h` used by `stb/stb_image.h`.
Since it is a library header (SIMD instruction) in gcc, the spdlog project cannot investigate why the compilation error occurs.

Please ask in the gcc project or stb project.

**Comment by pintodragon** [comment]
For what it is worth, I was able to get around this issue by switching my build chain to use clang instead of gcc.
