### ISSUE TITLE
VS2017 15.5 C++17 cannot instantiate abstract base class

### ISSUE THREAD

**Issue by VikingExplorer** [gabime/spdlog#572]
As part of getting my project to build with 15.5 C++17, I also had to upgrade from a previous version of spdlog to the one which is in vcpkg (0.14.0-1)

I'm getting: 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\memory(1847): error C2259: 'Couloir::WebApiSink': cannot instantiate abstract class
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\memory(1847): note: due to following members:
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include\memory(1847): note: 'void spdlog::sinks::base_sink<Mutex>::_flush(void)': is abstract

My class seems to be consistent with your current documentation:

`	class DebugTraceSink : public spdlog::sinks::base_sink < std::mutex >
	{
		public:
			void flush() override;
			void _sink_it( const spdlog::details::log_msg& msg ) override;
	};
`

**Comment by gabime** [comment]
_flush() is indeed abstract and need to be defined. 
The docs need to be updated..
