### PR TITLE
spdlog fails to build on GCC11 C++20

### PR DESCRIPTION
**Pull request by SuperCodeHero**
set options in gcc11:
set(CMAKE_CXX_STANDARD 20)

result:
[build] In file included from E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/details/spdlog_impl.h:11,
[build]                  from E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/spdlog.h:204,
[build]                  from E:\Project\testco\3rd\coroutine\src\Base\Log.cpp:6:
[build] E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/details/registry.h:31:23: error: expected unqualified-id before 'const'
[build]    31 |     registry_t<Mutex>(const registry_t<Mutex> &) = delete;
[build]       |                       ^~~~~
[build] E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/details/registry.h:31:23: error: expected ')' before 'const'
[build]    31 |     registry_t<Mutex>(const registry_t<Mutex> &) = delete;
[build]       |                      ~^~~~~
[build]       |                       )
[build] In file included from E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/details/spdlog_impl.h:11,
[build]                  from E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/spdlog.h:204,
[build]                  from E:\Project\testco\3rd\coroutine\src\Base\Log.cpp:6:
[build] E:/Project/testco/3rd/coroutine/build/_deps/spdlog-src/include/spdlog/details/registry.h:232:23: error: expected unqualified-id before ')' token
[build]   232 |     registry_t<Mutex>() = default;

### CODE REVIEW

**Comment by gabime** [comment]
I dont understand the problem nor the solution

**Comment by SuperCodeHero** [comment]
> 我不明白问题，也不了解解决方案

sorry, my English is terrible.
look at the example. There is a problem with such code
[https://godbolt.org/z/ET6fsdfsM](url)

**Comment by gabime** [comment]
It compiles with clang and msvc ang gcc10.3
could be be an issue with gcc11?
