### ISSUE TITLE
compilation error for pointer of user defined object with v1.9.2 and not with 1.8.0

### ISSUE THREAD

**Issue by romain-noel** [gabime/spdlog#2071]
I followed the documentation to log user defined types. It worked perfectly. However, when I tried to extend it to pointers, I get some trouble with v1.9.2 while it works with spdlog v1.8.0.

For example, if I take the following example:

    #include <spdlog/spdlog.h>    //
    #include "spdlog/sinks/stdout_color_sinks.h"
    #include "spdlog/fmt/ostr.h" // must be included to log object 

    using namespace std;

    struct my_type
    {
        int i;
        template<typename OStream>
        friend OStream &operator<<(OStream &os, const my_type &c)
        {
            return os << "[my_type i=" << c.i << "]";
        }
    };

    //
    template<typename OStream>
    OStream &operator<<(OStream &os,const my_type* c)
    {
        return os << "[my_type POINTER ]";
    }

    int main()	{ 
        
        auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        spdlog::logger logger("log_test", console_sink);
        logger.set_level(spdlog::level::trace);
        auto pLog =std::make_shared<spdlog::logger>(logger); //register

        std::unique_ptr<my_type> ptrA(new my_type{12});
        auto ptrB= ptrA.get();
        // pLog->info("user defined type object: {}", *ptrB);   // ok it works
        pLog->info("user defined type pointer: {}", ptrB);  

        return 0;
    }

It works perfectly with spdlog v1.8.0 while the compilation returns errors with spdlog v1.9.2. 
With `gcc 7.5` and `spdlog v1.9.2` using the compilation command `g++ -std=c++17 -o test_log.o -c test_log.cpp -Wall -O  -I../spdlog-v192` I get following errors (in short):
     
     ...
     spdlog-v192/fmt/bundled/core.h:1347:47: error: call of overloaded ‘map(my_type* const&)’ is ambiguous
                   typename Context::char_type>;

    ...
    spdlog-v192/fmt/bundled/core.h:1694:73: error: no matching function for call to fmt::v8::detail::arg_data<fmt::v8::detail::value<fmt::v8::basic_format_context<fmt::v8::appender, char> >, char, 1, 0>::arg_data(<brace-enclosed initializer list>)
             detail::mapped_type_constant<Args, Context>::value>(args)...} {

    ... 
    spdlog-v192/fmt/bundled/core.h:1679:39: error: constexpr call flows off the end of the function
       static constexpr unsigned long long desc =
