### ISSUE TITLE
Conflict with Boost.Asio

### ISSUE THREAD

**Issue by Chnossos** [gabime/spdlog#179]
Hi,

Compiling the following source file with Microsoft Visual C++ 2015 and Boost 1.60.0:

    #include <spdlog/spdlog.hpp>
    #include <boost/asio.hpp>

displays the following error:

> #error directive: WinSock.h has already been included (c:\C++\boost\boost_1_60_0\boost\asio\detail\socket_types.hpp:24)

**Comment by crackedmind** [comment]
Spdlog don't use winsock librrary. Check that you didn't include Winsock2.h before asio.

**Comment by RavenX8** [comment]
I have this same issue. Before I added spdlog, I could compile just fine. After changing adding the include file, I keep getting this error. The only way to fix it that I could see was to not use this lib.

**Comment by gabime** [comment]
I will forward this to cppformat lib. seems the file[ spdlog/details/format.cc](https://github.com/gabime/spdlog/blob/a9fb96e088d48d000c130eaff70e0661a6316880/include/spdlog/details/format.cc) includes windows.h without defining WIN32_LEAN_AND_MEAN

**Comment by vitaut** [comment]
As mentioned in https://github.com/cppformat/cppformat/issues/297, I don't think `WIN32_LEAN_AND_MEAN` should be defined in a header because it can break some users. Since the error is generated by asio which wants to include `winsock.h` first, I think a better solution is to reorder the includes:

```
#include <boost/asio.hpp>
#include <spdlog/spdlog.hpp>
```

This requirement should probably be documented in Boost asio somewhere.

**Comment by gabime** [comment]
Fixed in 79451368cfdc5be150b5bb6dc4bbbdc078d8cd8b

**Comment by gcerretani** [comment]
The same bug reappeared in version v1.6.0.

This source code

```
#include <spdlog/spdlog.h>
#include <boost/asio.hpp>
```

compiles in v1.5.0, but fails since v1.6.0 with messages like

>  fatal error C1189: #error:  WinSock.h has already been included.

 Tested up to v1.8.0 with Boost v1.67 and MSVC 1900 (2015).
