### ISSUE TITLE
spdlog-1.9.2 tests fails to build on systems with glibc 2.34 due to bundled catch

### ISSUE THREAD

**Issue by marv** [gabime/spdlog#2058]
```
cd /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/build/tests && /usr/bin/x86_64-pc-linux-gnu-c++ -DFMT_LOCALE -DFMT_SHARED -DSPDLOG_COMPILED_LIB -D
SPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/include -pipe -O2 -mtune=generic -march=x86-64
 -std=c++11 -MD -MT tests/CMakeFiles/spdlog-utests.dir/test_systemd.cpp.o -MF CMakeFiles/spdlog-utests.dir/test_systemd.cpp.o.d -o CMakeFiles/spdlog-ut
ests.dir/test_systemd.cpp.o -c /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/test_systemd.cpp
In file included from /usr/x86_64-pc-linux-gnu/include/signal.h:328,
                 from /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/catch.hpp:6323,
                 from /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/main.cpp:2:
/var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/catch.hpp:9041:58: error: call to non-'constexpr' function 'long int sysconf(int)'
 9041 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/x86_64-pc-linux-gnu/include/bits/sigstksz.h:24,
                 from /usr/x86_64-pc-linux-gnu/include/signal.h:328,
                 from /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/catch.hpp:6323,
                 from /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/main.cpp:2:
/usr/x86_64-pc-linux-gnu/include/unistd.h:641:17: note: 'long int sysconf(int)' declared here
  641 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/main.cpp:2:
/var/tmp/paludis/build/dev-libs-spdlog-1.9.2/work/spdlog-1.9.2/tests/catch.hpp:9100:45: error: size of array 'altStackMem' is not an integral constant-expression
 9100 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[2]: *** [tests/CMakeFiles/spdlog-utests.dir/build.make:219: tests/CMakeFiles/spdlog-utests.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

It's already fixed upstream[1], so it's only a matter of updating the bundled catch version

[1] catchorg/Catch2#2178
