### ISSUE TITLE
warning: type attributes ignored after type is already defined

### ISSUE THREAD

**Issue by aengusjiang** [gabime/spdlog#2332]
build on cenots7.9

async.cpp:13:44: warning: type attributes ignored after type is already defined

**Comment by gabime** [comment]
please provide full compiler message and compiler version

**Comment by aengusjiang** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.

and the spdlog version:1.10

**Comment by aengusjiang** [comment]
![image](https://user-images.githubusercontent.com/22406984/162602304-1ec07605-1753-45bd-8b95-69044221eae3.png)
the higher gcc version has the same issue too.

the solution is comment the line async.cpp:13

**Comment by Delgan** [comment]
I face the same issue with `v1.10.0` using GCC 8.4.0 on Ubuntu 18.04:

```
[build] FAILED: _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o 
[build] /usr/bin/x86_64-linux-gnu-g++-8 -DFMT_EXPORT -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_SHARED_LIB -Dspdlog_EXPORTS -I_deps/spdlog-build/spdlog_autogen/include -I_deps/spdlog-src/include -pedantic -Wextra -Wfloat-conversion -Wnon-virtual-dtor -z defs -Wall -Werror -g -fPIC -std=c++17 -MD -MT _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o -MF _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o.d -o _deps/spdlog-build/CMakeFiles/spdlog.dir/src/async.cpp.o -c _deps/spdlog-src/src/async.cpp
[build] _deps/spdlog-src/src/async.cpp:13:44: error: type attributes ignored after type is already defined [-Werror=attributes]
[build]  template class SPDLOG_API spdlog::details::mpmc_blocking_queue<spdlog::details::async_msg>;
[build]                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build] cc1plus: all warnings being treated as errors
```

**Comment by aengusjiang** [comment]
This issue is fixed, waiting to merge.

**Comment by Delgan** [comment]
The template is implicitly defined here: https://github.com/gabime/spdlog/blob/76fb40d95455f249bd70824ecfcae7a8f0930fa3/include/spdlog/details/thread_pool.h#L84-L103

This explains the warning when the same template is explicitly defined in `async.cpp`: https://github.com/gabime/spdlog/blob/76fb40d95455f249bd70824ecfcae7a8f0930fa3/src/async.cpp#L13

I tried to use `extern template class` inside `async.cpp` to disable implicit instantiation but this did not make the warning disappear. This might because of this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81764

**Comment by aengusjiang** [comment]
> The template is implicitly defined here:
> 
> https://github.com/gabime/spdlog/blob/76fb40d95455f249bd70824ecfcae7a8f0930fa3/include/spdlog/details/thread_pool.h#L84-L103
> 
> This explains the warning when the same template is explicitly defined in `async.cpp`:
> 
> https://github.com/gabime/spdlog/blob/76fb40d95455f249bd70824ecfcae7a8f0930fa3/src/async.cpp#L13
> 
> I tried to use `extern template class` inside `thread_pool.h` to disable implicit instantiation but this did not make the warning disappear. This might because of this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81764

<==
What about not duplicate declare "template class SPDLOG_API spdlog::details::mpmc_blocking_queue<spdlog::details::async_msg>; " in async.cpp file?

**Comment by Delgan** [comment]
@aengusjiang This is maybe a solution, but I think explicit template instantiation aren't allowed inside header files, and I don't know if `SPDLOG_API` is compatible with implicit template instantiation. Also, it means we lose consistency with other templates instantiation which is a bit "ugly".

**Comment by gabime** [comment]
Fixed in pr #2336
