### ISSUE TITLE
spdlog fails to build on Clang 13.0 Xcode 13.2

### ISSUE THREAD

**Issue by batuhanbozyel** [gabime/spdlog#2212]
Clang cannot resolve templated functions, thus fails to compile

- Clang 13.0
- Xcode 13.2
- C++20

```
In file included from /Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/Core/Window.cpp:1:
In file included from /Users/tunti/Desktop/Projects/GleamEngine/build/Engine/Source/Runtime/CMakeFiles/Runtime.dir/Debug/cmake_pch.hxx:5:
In file included from /Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/gpch.h:39:
/Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/IO/Log.h:24:63: error: call to consteval function 'fmt::basic_format_string<char, char const (&)[84], int, char const (&)[24]>::basic_format_string<char [39], 0>' is not a constant expression
    static void Critical(Args&& ... args) { sLogger->critical(std::forward<Args>(args)...); }
                                                              ^
/Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/Core/Window.cpp:23:2: note: in instantiation of function template specialization 'Gleam::Log::Critical<char const (&)[39], char const (&)[84], int, char const (&)[24]>' requested here
        GLEAM_ASSERT(mWindow, "Window creation failed!");
        ^
In file included from /Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/Core/Window.cpp:1:
In file included from /Users/tunti/Desktop/Projects/GleamEngine/build/Engine/Source/Runtime/CMakeFiles/Runtime.dir/Debug/cmake_pch.hxx:5:
In file included from /Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/gpch.h:21:
/Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/Core/EngineDefines.h:23:59: note: expanded from macro 'GLEAM_ASSERT'
    #define GLEAM_ASSERT(x, ...) if (!(x)) { Gleam::Log::Critical("Assertion failed at {0}:{1} reason {2}", __FILE__, __LINE__, __VA_ARGS__); DEBUGBREAK(); }
                                                         ^
In file included from /Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/Core/Window.cpp:1:
In file included from /Users/tunti/Desktop/Projects/GleamEngine/build/Engine/Source/Runtime/CMakeFiles/Runtime.dir/Debug/cmake_pch.hxx:5:
In file included from /Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/gpch.h:39:
/Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/IO/Log.h:24:82: note: function parameter 'args' with unknown value cannot be used in a constant expression
    static void Critical(Args&& ... args) { sLogger->critical(std::forward<Args>(args)...); }
                                                                                 ^
/Users/tunti/Desktop/Projects/GleamEngine/Engine/Source/Runtime/src/IO/Log.h:24:37: note: declared here
    static void Critical(Args&& ... args) { sLogger->critical(std::forward<Args>(args)...); }
                                    ^
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-macos12.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg:
```

my wrapper class over spdlog and assert macro:

```
class Log
{
public:
    static void Init();
    
    template<typename ... Args>
    static void Trace(Args&& ... args) { sLogger->trace(std::forward<Args>(args)...); }

    template<typename ... Args>
    static void Info(Args&& ... args) { sLogger->info(std::forward<Args>(args)...); }

    template<typename ... Args>
    static void Warn(Args&& ... args) { sLogger->warn(std::forward<Args>(args)...); }

    template<typename ... Args>
    static void Error(Args&& ... args) { sLogger->error(std::forward<Args>(args)...); }

    template<typename ... Args>
    static void Critical(Args&& ... args) { sLogger->critical(std::forward<Args>(args)...); }

private:

    static inline Ref<spdlog::logger> sLogger = nullptr;

};

#ifdef ENABLE_ASSERTS
    #define GLEAM_ASSERT(x, ...) if (!(x)) { Gleam::Log::Critical("Assertion failed at {0}:{1} reason {2}", __FILE__, __LINE__, __VA_ARGS__); DEBUGBREAK(); }
#else
    #define GLEAM_ASSERT(...)
#endif
```

**Comment by gabime** [comment]
Closing due to inactivity.
