### ISSUE TITLE
error: ‘template<class T, class ... Args> fmt::v11::basic_string_view<Char> spdlog::details::to_string_view’ redeclared as different kind of entity

### ISSUE THREAD

**Issue by KarlStraussberger** [gabime/spdlog#3302]
Occurs when building gerbera with fmt 11.1

https://github.com/gerbera/gerbera/actions/runs/12498488888

```
In file included from /build/spdlog-1.15.0/include/spdlog/logger.h:17, 
     from /build/spdlog-1.15.0/include/spdlog/async_logger.h:17, 
     from /build/spdlog-1.15.0/include/spdlog/async.h:17, 
     from /build/spdlog-1.15.0/src/stdout_sinks.cpp:10: 
/build/spdlog-1.15.0/include/spdlog/common.h:369:1: warning: inline variables are only available with '-std=c++17' or '-std=gnu++17' [-Wc++17-extensions] 
369 | inline fmt::basic_string_view<T> to_string_view(fmt::basic_format_string<T, Args...> fmt) { 
| ^~~~~~

/build/spdlog-1.15.0/include/spdlog/common.h:369:54: error: ‘template<class T, class ... Args> fmt::v11::basic_string_view<Char> spdlog::details::to_string_view’ redeclared as different kind of entity
  369 | inline fmt::basic_string_view<T> to_string_view(fmt::basic_format_string<T, Args...> fmt) {
      |                                                      ^~~~~~~~~~~~~~~~~~~
```

Seems some compiler selection is broken.

I'm not quite sure that it's spdlog that's causing the issue because it worked well with fmt 11.0.2.

_Originally posted by @vitaut in https://github.com/fmtlib/fmt/issues/4275#issuecomment-2562854805_

**Comment by tt4g** [comment]
Maybe already fixed (#3301).

**Comment by KarlStraussberger** [comment]
Works. Thank you.
