### ISSUE TITLE
Compilation issue with spdlog 1.15.x and clang++ 20.1.7

### ISSUE THREAD

**Issue by uweseimet** [gabime/spdlog#3418]
After updating from clang++ 19.1.7 to 20.1.7 (on Linux) there are compilation errors like this one:
```
In file included from /usr/include/spdlog/spdlog.h:12:
In file included from /usr/include/spdlog/common.h:50:
In file included from /usr/include/spdlog/fmt/fmt.h:28:
In file included from /usr/include/fmt/core.h:5:
In file included from /usr/include/fmt/format.h:4417:
/usr/include/fmt/format-inl.h:59:24: error: call to consteval function 'fmt::basic_format_string<char, fmt::basic_string_view<char> &, const char (&)[3]>::basic_format_string<FMT_COMPILE_STRING, 0>' is not a constant expression
   59 |     fmt::format_to(it, FMT_STRING("{}{}"), message, SEP);
      |                        ^
/usr/include/fmt/format.h:1827:23: note: expanded from macro 'FMT_STRING'
 1827 | #define FMT_STRING(s) FMT_STRING_IMPL(s, fmt::detail::compile_string, )
      |                       ^
/usr/include/fmt/format.h:1806:3: note: expanded from macro 'FMT_STRING_IMPL'
 1806 |   [] {                                                                        \
      |   ^
/usr/include/fmt/base.h:779:54: note: subexpression not valid in a constant expression
  779 |     format_str_.remove_prefix(detail::to_unsigned(it - begin()));
      |                                                   ~~~^~~~~~~~~
...
```
Is there any spdlog setting that addresses these errors? Currently I use "-DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL", which has worked fine so far with g++ and older versions of clang++ but now results in these errors.

**Comment by tt4g** [comment]
Duplicate #3417 (fmtlib/fmt#4396)

You must use fmt v11.2.0 or above.

**Comment by uweseimet** [comment]
Yes, this works fine, thank you. I missed that my problem was related to fmt and not to spdlog.
