### ISSUE TITLE
gcc 4.8.5 compilation failure

### ISSUE THREAD

**Issue by rafiw** [gabime/spdlog#759]
```

In file included from ../../../src/utils/logger/spdlog/details/../details/../details/async_logger_impl.h:12:0,
                 from ../../../src/utils/logger/spdlog/details/../details/../async_logger.h:72,
                 from ../../../src/utils/logger/spdlog/details/../details/registry.h:13,
                 from ../../../src/utils/logger/spdlog/details/spdlog_impl.h:11,
                 from ../../../src/utils/logger/spdlog/spdlog.h:204,
                 from ../../../src/utils/logger/logger_wrapper.h:17,
                 from XXXXX:16:
../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h: In instantiation of ‘bool spdlog::details::mpmc_bounded_queue<T>::dequeue_for(T&, std::chrono::milliseconds) [with T = spdlog::details::async_log_helper::async_msg; std::chrono::milliseconds = std::chrono::duration<long int, std::ratio<1l, 1000l> >]’:
../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h:256:79:   required from here
../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h:46:12: error: unused parameter ‘other’ [-Werror=unused-parameter]
     struct async_msg
            ^
In file included from ../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h:17:0,
                 from ../../../src/utils/logger/spdlog/details/../details/../details/async_logger_impl.h:12,
                 from ../../../src/utils/logger/spdlog/details/../details/../async_logger.h:72,
                 from ../../../src/utils/logger/spdlog/details/../details/registry.h:13,
                 from ../../../src/utils/logger/spdlog/details/spdlog_impl.h:11,
                 from ../../../src/utils/logger/spdlog/spdlog.h:204,
                 from ../../../src/utils/logger/logger_wrapper.h:17,
                 from XXXX.cpp:16:
../../../src/utils/logger/spdlog/details/../details/../details/../details/../details/mpmc_blocking_q.h:68:25: note: synthesized method ‘spdlog::details::async_log_helper::async_msg& spdlog::details::async_log_helper::async_msg::operator=(spdlog::details::async_log_helper::async_msg&&)’ first required here
             popped_item = std::move(q_.front());
                         ^
In file included from ../../../src/utils/logger/spdlog/details/../details/../details/async_logger_impl.h:12:0,
                 from ../../../src/utils/logger/spdlog/details/../details/../async_logger.h:72,
                 from ../../../src/utils/logger/spdlog/details/../details/registry.h:13,
                 from ../../../src/utils/logger/spdlog/details/spdlog_impl.h:11,
                 from ../../../src/utils/logger/spdlog/spdlog.h:204,
                 from ../../../src/utils/logger/logger_wrapper.h:17,
                 from XXXXX.cpp:16:
../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = spdlog::details::async_log_helper::async_msg; _Args = {spdlog::details::async_log_helper::async_msg}; _Tp = spdlog::details::async_log_helper::async_msg]’:
/usr/include/c++/4.8.2/bits/deque.tcc:137:6:   required from ‘void std::deque<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {spdlog::details::async_log_helper::async_msg}; _Tp = spdlog::details::async_log_helper::async_msg; _Alloc = std::allocator<spdlog::details::async_log_helper::async_msg>]’
/usr/include/c++/4.8.2/bits/stl_deque.h:1405:36:   required from ‘void std::deque<_Tp, _Alloc>::push_back(std::deque<_Tp, _Alloc>::value_type&&) [with _Tp = spdlog::details::async_log_helper::async_msg; _Alloc = std::allocator<spdlog::details::async_log_helper::async_msg>; std::deque<_Tp, _Alloc>::value_type = spdlog::details::async_log_helper::async_msg]’
/usr/include/c++/4.8.2/bits/stl_queue.h:218:9:   required from ‘void std::queue<_Tp, _Sequence>::push(std::queue<_Tp, _Sequence>::value_type&&) [with _Tp = spdlog::details::async_log_helper::async_msg; _Sequence = std::deque<spdlog::details::async_log_helper::async_msg, std::allocator<spdlog::details::async_log_helper::async_msg> >; std::queue<_Tp, _Sequence>::value_type = spdlog::details::async_log_helper::async_msg]’
../../../src/utils/logger/spdlog/details/../details/../details/../details/../details/mpmc_blocking_q.h:37:13:   required from ‘void spdlog::details::mpmc_bounded_queue<T>::enqueue(T&&) [with T = spdlog::details::async_log_helper::async_msg]’
../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h:216:38:   required from here
../../../src/utils/logger/spdlog/details/../details/../details/../details/async_log_helper.h:66:9: error: unused parameter ‘other’ [-Werror=unused-parameter]
         async_msg(async_msg &&other) = default;
         ^
In file included from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++allocator.h:33:0,
                 from /usr/include/c++/4.8.2/bits/allocator.h:46,
                 from /usr/include/c++/4.8.2/vector:61,
                 from XXXXX.cpp:16:
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4: note: synthesized method ‘spdlog::details::async_log_helper::async_msg::async_msg(spdlog::details::async_log_helper::async_msg&&)’ first required here
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^

```

i know it's a compiler issue since it compiles well with clang.

**Comment by gabime** [comment]
looks like it caused because of -Werror=unused-parameter flag.
Anyway, the active branch is v1.x - please see if it is ok there.

**Comment by rafiw** [comment]
still get an error
`[  9%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/errors.cpp.o
In file included from /git/spdlog/include/spdlog/async.h:21:0,
                 from /git/spdlog/tests/includes.h:15,
                 from /git/spdlog/tests/errors.cpp:4:
/git/spdlog/include/spdlog/details/registry.h: In instantiation of ‘static spdlog::details::registry_t<Mutex>& spdlog::details::registry_t<Mutex>::instance() [with Mutex = std::mutex]’:
/git/spdlog/include/spdlog/async.h:79:15:   required from here
/git/spdlog/include/spdlog/details/registry.h:172:5: error: converting to ‘std::unique_ptr<spdlog::formatter>’ from initializer list would use explicit constructor ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>::pointer) [with _Tp = spdlog::formatter; _Dp = std::default_delete<spdlog::formatter>; std::unique_ptr<_Tp, _Dp>::pointer = spdlog::formatter*]’
     registry_t<Mutex>() = default;
     ^
/git/spdlog/include/spdlog/details/registry.h:167:34: note: synthesized method ‘spdlog::details::registry_t<Mutex>::registry_t() [with Mutex = std::mutex]’ first required here
         static registry_t<Mutex> s_instance;
                                  ^
make[2]: *** [tests/CMakeFiles/spdlog-utests.dir/errors.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/spdlog-utests.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by rafiw** [comment]
it looks like this is the first bad commit
8338b45b2b83a206a3168c0c3ff488555038c112 is the first bad commit

```
commit 8338b45b2b83a206a3168c0c3ff488555038c112
Author: gabime <gmelman1@gmail.com>
Date:   Sun May 27 02:53:16 2018 +0300

    added tp->wait_empty()
````
but it gives a different error

`In file included from /git/spdlog/tests/test_async.cpp:4:0:
/git/spdlog/tests/test_sink.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = spdlog::sinks::test_sink<std::mute     x>; _Args = {}; _Tp = spdlog::sinks::test_sink<std::mutex>]’:
/usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::va     lue, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = spdlog::sinks::test_sink<std::mutex>; _Args = {}; _Alloc = std     ::allocator<spdlog::sinks::test_sink<std::mutex> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = voi     d]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__ar     gs)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = spdlog::sinks::test_sink<std::mutex>; _Args = {}; _Alloc = std::allocator     <spdlog::sinks::test_sink<std::mutex> >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8.2/bits/shared_ptr_base.h:400:38:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...)      [with _Args = {}; _Tp = spdlog::sinks::test_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::test_sink<std::mutex> >; __gnu_cxx::_Lock_policy _Lp = (__gnu     _cxx::_Lock_policy)2u]’
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Sp_counted_pt     r_inplace<spdlog::sinks::test_sink<std::mutex>, std::allocator<spdlog::sinks::test_sink<std::mutex> >, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<     spdlog::sinks::test_sink<std::mutex> >}; _Tp = std::_Sp_counted_ptr_inplace<spdlog::sinks::test_sink<std::mutex>, std::allocator<spdlog::sinks::test_sink<std::mute     x> >, (__gnu_cxx::_Lock_policy)2u>]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/4.8.2/bits/shared_ptr_base.h:503:37:   required from ‘std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Arg     s&& ...) [with _Tp = spdlog::sinks::test_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::test_sink<std::mutex> >; _Args = {}; __gnu_cxx::_Lock_policy _Lp      = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/4.8.2/bits/shared_ptr_base.h:957:35:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& .     ..) [with _Alloc = std::allocator<spdlog::sinks::test_sink<std::mutex> >; _Args = {}; _Tp = spdlog::sinks::test_sink<std::mutex>; __gnu_cxx::_Lock_policy _Lp = (__     gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/4.8.2/bits/shared_ptr.h:316:64:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _All     oc = std::allocator<spdlog::sinks::test_sink<std::mutex> >; _Args = {}; _Tp = spdlog::sinks::test_sink<std::mutex>]’
/usr/include/c++/4.8.2/bits/shared_ptr.h:598:39:   required from ‘std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = spdlog::sinks:     :test_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::test_sink<std::mutex> >; _Args = {}]’
/usr/include/c++/4.8.2/bits/shared_ptr.h:614:42:   required from ‘std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = spdlog::sinks::test_sink<std::mut     ex>; _Args = {}]’
/git/spdlog/tests/test_async.cpp:9:60:   required from here
/git/spdlog/tests/test_sink.h:19:7: error: converting to ‘const std::chrono::duration<long int, std::ratio<1l, 1000l> >’ from initializer list would use explicit c     onstructor ‘constexpr std::chrono::duration<_Rep, _Period>::duration(const _Rep2&) [with _Rep2 = int; <template-parameter-2-2> = void; _Rep = long int; _Period = s     td::ratio<1l, 1000l>]’
 class test_sink : public base_sink<Mutex>
       ^
In file included from /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++allocator.h:33:0,
                 from /usr/include/c++/4.8.2/bits/allocator.h:46,
                 from /usr/include/c++/4.8.2/string:41,
                 from /usr/include/c++/4.8.2/bits/locale_classes.h:40,
                 from /usr/include/c++/4.8.2/bits/ios_base.h:41,
                 from /usr/include/c++/4.8.2/ios:42,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/sstream:38,
                 from /git/spdlog/tests/catch.hpp:65,
                 from /git/spdlog/tests/includes.h:3,
                 from /git/spdlog/tests/test_async.cpp:1:
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4: note: synthesized method ‘constexpr spdlog::sinks::test_sink<std::mutex>::test_sink()’ first required here
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
make[2]: *** [tests/CMakeFiles/spdlog-utests.dir/test_async.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/spdlog-utests.dir/all] Error 2
`

**Comment by gabime** [comment]
Fixed. Please try again from  latest commit.

**Comment by rafiw** [comment]
@gabime fixed thanks!
