### ISSUE TITLE
[V1.0.0] Can't find functional header on Linux

### ISSUE THREAD

**Issue by bkotzz** [gabime/spdlog#940]
Can't compile on linux with gcc for version 1.0.0 because of this:
```
spdlog.h:71:133: error: 'function' in namespace 'std' does not name a template type
 void set_async_mode(size_t queue_size, const async_overflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
                                                                                                                                     ^~~~~~~~
spdlog.h:71:128: note: 'std::function' is defined in header '<functional>'; did you forget to #include <functional>'?
/spdlog.h:34:1:
+#include <functional>
 
/spdlog.h:71:128:
 void set_async_mode(size_t queue_size, const async_overflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
                                                                                                                                ^~~
/spdlog.h:71:141: error: expected ',' or '...' before '<' token
 void set_async_mode(size_t queue_size, const async_overflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
                                                                                                                                             ^
/spdlog.h:71:6: error: default argument missing for parameter 3 of 'void spdlog::set_async_mode(size_t, spdlog::async_overflow_policy, int)'
 void set_async_mode(size_t queue_size, const async_overflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
      ^~~~~~~~~~~~~~
/spdlog/details/spdlog_impl.h:140:197: error: 'void spdlog::set_async_mode(size_t, spdlog::async_overflow_policy, const std::function<void()>&, const milliseconds&)' should have been declared inside 'spdlog'
 inline void spdlog::set_async_mode(size_t queue_size, const async_overflow_policy overflow_policy, const std::function<void()>& worker_warmup_cb, const std::chrono::milliseconds& flush_interval_ms)
                                                                                                                                                                                                     ^
/spdlog.h:71:133: error: 'function' in namespace 'std' does not name a template type
 verflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
                                                                                 ^~~~~~~~

/spdlog.h:71:128: note: 'std::function' is defined in header '<functional>'; did you forget to #include <functional>'?
/spdlog.h:34:1:
+#include <functional>
 

/spdlog.h:71:128:
 ync_overflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
                                                                                 ^~~
/spdlog.h:71:141: error: expected ',' or '...' before '<' token
 policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
                                                                                 ^

/spdlog.h:71:6: error: default argument missing for parameter 3 of 'void spdlog::set_async_mode(size_t, spdlog::async_overflow_policy, int)'
 void set_async_mode(size_t queue_size, const async_overflow_policy overflow_policy = async_overflow_policy::block_retry, const std::function<void()>& worker_warmup_cb = nullptr, const std::chrono::milliseconds& flush_interval_ms = std::chrono::milliseconds::zero());
      ^~~~~~~~~~~~~~
spdlog/details/spdlog_impl.h:140:197: error: 'void spdlog::set_async_mode(size_t, spdlog::async_overflow_policy, const std::function<void()>&, const milliseconds&)' should have been declared inside 'spdlog'
 td::function<void()>& worker_warmup_cb, const std::chrono::milliseconds& flush_interval_ms

```

Works fine by putting `#include<functional>` before the `spdlog.h` include

**Comment by gabime** [comment]
There is no set_async_mode in v1.x
