### ISSUE TITLE
spdlog/fmt/bundled/core.h:472:150: error: 'constexpr ... when compiling a .cu file with nvcc

### ISSUE THREAD

**Issue by EajksEajks** [gabime/spdlog#2893]
Hi,

compilation platform ubuntu 22.04 + intel oneapi 2023.2 + nvidia cuda 12.2
spdlog v1.10.0...v1.12.0 used in its header version.
spdlog as submodule in a bigger C++ + CUDA project.

Pure C++ files using spdlog compiled successfully with gcc or icx from Intel.
CU files using spdlog compiled with cuda 12.2 failed on a constexpr in fmt.

All files are compiled using C++20.

I'm looking for a workaround but have found none till now.

**Comment by EajksEajks** [comment]
Strange enough same code compiles on win11 + intel oneapi 2023.2 + cuda 12.2...

**Comment by tt4g** [comment]
`spdlog/fmt/bundled/core.h` fmt library source. Please open issue in [fmt project](https://github.com/fmtlib/fmt).

**Comment by prospero-x** [comment]
Same issue building with v1.12.0 on SUSE linux with gcc v11.2.0. I get the error in: 
```spdlog/common.h:351:30: error: call to non-'constexpr' function 'const T* fmt::v9::detail::buffer<T>::data() const [with T = char]'
  351 |     return spdlog::string_view_t{buf.data(), buf.size()};
```

It can compile successfully when I revert to spdlog v1.11.0.

**Comment by tt4g** [comment]
@prospero-x No error message so I don't know anything, but probably a duplicate #2693 (already fixed #2694).

**Comment by EajksEajks** [comment]
Sorry I forgot the error code
```
...
128.0 /src/code/sdk/dependencies/spdlog/include/spdlog/fmt/bundled/core.h:348:14: error: call to non-'constexpr' function 'void fmt::v9::detail::ignore_unused(const T& ...) [with T = {bool}]'
128.0   348 |   ignore_unused(default_value);
128.0       |   ~~~~~~~~~~~^~~~~~~~~~~~~~~
...
128.0 /src/code/sdk/dependencies/spdlog/include/spdlog/fmt/bundled/format.h:1099:29: error: call to non-'constexpr' function 'int fmt::v9::detail::count_digits_fallback(T) [with T = long unsigned int]'
128.0  1099 |   return count_digits_fallback(n);
128.0       |        ~~~~~~~~~~~~~~~~~~~~~^~~
...
```

I can open an issue in the fmt project but could you tell me which fmt version is bundled with spdlog, please?

**Comment by tt4g** [comment]
fmt version is 9.1.0 in spdlog 1.12.0.
And this problem is already fixed in fmt 10.1.0 or above.

fmt issue: fmtlib/fmt#3543
fmt PR: fmtlib/fmt#3544

**Comment by EajksEajks** [comment]
Do you plan to move from fmt 9.1.0 to 1.12.0 in the near future?

**Comment by tt4g** [comment]
I don't now.
But you can use external fmt by CMake variable `SPDLOG_FMT_EXTERNAL`.

https://github.com/gabime/spdlog/blob/91807c2e718890ca2c0c88620326c6919ce041f4/CMakeLists.txt#L91-L92

**Comment by EajksEajks** [comment]
It's something I've tried but it doesn't work yet and I don't know why. I'm using spdlog 1.12.0 as a submodule of a bigger project. I tried both combinations (SPDLOG_FMT_EXTERNAL=ON and spdlog::spdlog) and (SPDLOG_FMT_EXTERNAL_HO=ON and spdlog::spdlog_header_only) but it still uses the bundled fmt. I'm still trying tot figure out why.

**Comment by tt4g** [comment]
There are many reports of using spdlog version 1.12.0 and external fmt, so it is a configuration problem with your CMake project.

**Comment by EajksEajks** [comment]
Maybe... but whatever I do to change the SPDLOG_FMT_EXTERNAL or SPDLOG_FMT_EXTERNAL_HO variable, cmake still picks the bundled fmt. Even changing the default option value in your code doesn't change this behavior.

**Comment by tt4g** [comment]
@EajksEajks Did you know that CMake variables are cached?
If you change an optional variable, it will not be updated unless you delete the cache.
If you do not understand the cache, please delete the CMake build directory and build again.

**Comment by EajksEajks** [comment]
I know they are cached. The whole project is rebuilt within a docker container every time ; the docker cache is disabled so we rebuild from the base image and redo all build steps.

**Comment by tt4g** [comment]
Docker also has a build cache, so the build cache must be disabled.
Make sure that `SPDLOG_FMT_EXTERNAL` is true before building spdlog.

In any case, that is a CMake issue and any further questions should be made on StackOverflow or the CMake project.
